twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        resources_url: '%resourcesUrl%'
        breadcrumb: '@App\UI\Menus\Breadcrumb\Breadcrumb'

when@test:
    twig:
        strict_variables: true
