twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        resources_url: '%resources_url%'
        site_logo_path: '%site_logo_path%'
        breadcrumb: '@App\UI\Menus\Breadcrumb\Breadcrumb'
        header_submenus: '@App\UI\Menus\Header\HeaderMenus'

when@test:
    twig:
        strict_variables: true
